version: "3.9"
services:
  web:
    build: .
    image: web:latest
    ports:
      - "3000:5000"
    #volumes:
      #- ./app:/geoinfo/app
  postgis:
    env_file:
      - database.conf
    image: postgis/postgis
    restart: on-failure
    ports:
      - "3333:5432"
    volumes:
      - pg_data:/var/lib/postgresql
volumes:
  pg_data: